version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    privileged: true
    user: root
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - jenkinsNetwork

networks:
  jenkinsNetwork:


